apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mautrix-signal.fullname" . }}
  labels:
    {{- include "mautrix-signal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mautrix-signal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mautrix-signal.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- $configKey := default "config.yaml" .Values.configMap.configKey }}
      {{- $configFileName := default "config.yaml" .Values.configMap.configFileName }}
      {{- $registrationKey := default "registration.yaml" .Values.configMap.registrationKey }}
      {{- $registrationFileName := default "registration.yaml" .Values.configMap.registrationFileName }}
      {{- $needsItems := or (or (ne $configKey "config.yaml") (ne $configFileName "config.yaml")) (or (ne $registrationKey "registration.yaml") (ne $registrationFileName "registration.yaml")) }}
      serviceAccountName: {{ include "mautrix-signal.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: copy-config
          image: {{ default "busybox:1.36.1" .Values.initContainers.copyConfig.image }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.initContainers.copyConfig.imagePullPolicy }}
          command:
            - sh
            - -c
            - |
              set -eu
              if [ -f "/config-src/{{ $configFileName }}" ]; then cp "/config-src/{{ $configFileName }}" "/data/{{ $configFileName }}"; fi
              if [ -f "/config-src/{{ $registrationFileName }}" ]; then cp "/config-src/{{ $registrationFileName }}" "/data/{{ $registrationFileName }}"; fi
          volumeMounts:
            - name: config
              mountPath: /config-src
            - name: data
              mountPath: /data
      containers:
        - name: {{ include "mautrix-signal.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "mautrix-signal.configMapName" . }}
            {{- if $needsItems }}
            items:
              - key: {{ $configKey }}
                path: {{ $configFileName }}
              - key: {{ $registrationKey }}
                path: {{ $registrationFileName }}
            {{- end }}
        - name: data
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
